/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalReportRouteImport } from './routes/legal.report'
import { Route as LegalProhibitedRouteImport } from './routes/legal.prohibited'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalNoticesRouteImport } from './routes/legal.notices'
import { Route as LegalGuideRouteImport } from './routes/legal.guide'
import { Route as LegalFaqRouteImport } from './routes/legal.faq'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReportRoute = LegalReportRouteImport.update({
  id: '/legal/report',
  path: '/legal/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalProhibitedRoute = LegalProhibitedRouteImport.update({
  id: '/legal/prohibited',
  path: '/legal/prohibited',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticesRoute = LegalNoticesRouteImport.update({
  id: '/legal/notices',
  path: '/legal/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalGuideRoute = LegalGuideRouteImport.update({
  id: '/legal/guide',
  path: '/legal/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFaqRoute = LegalFaqRouteImport.update({
  id: '/legal/faq',
  path: '/legal/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/me': typeof AuthenticatedMeRoute
  '/sell': typeof AuthenticatedSellRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/guide': typeof LegalGuideRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/prohibited': typeof LegalProhibitedRoute
  '/legal/report': typeof LegalReportRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/': typeof ListingsIndexRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/me': typeof AuthenticatedMeRoute
  '/sell': typeof AuthenticatedSellRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/guide': typeof LegalGuideRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/prohibited': typeof LegalProhibitedRoute
  '/legal/report': typeof LegalReportRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings': typeof ListingsIndexRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/guide': typeof LegalGuideRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/prohibited': typeof LegalProhibitedRoute
  '/legal/report': typeof LegalReportRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/': typeof ListingsIndexRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/search'
    | '/welcome'
    | '/admin'
    | '/favorites'
    | '/me'
    | '/sell'
    | '/category/$slug'
    | '/legal/faq'
    | '/legal/guide'
    | '/legal/notices'
    | '/legal/privacy'
    | '/legal/prohibited'
    | '/legal/report'
    | '/legal/terms'
    | '/listings/$id'
    | '/listings/'
    | '/messages/$id'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/search'
    | '/welcome'
    | '/admin'
    | '/favorites'
    | '/me'
    | '/sell'
    | '/category/$slug'
    | '/legal/faq'
    | '/legal/guide'
    | '/legal/notices'
    | '/legal/privacy'
    | '/legal/prohibited'
    | '/legal/report'
    | '/legal/terms'
    | '/listings/$id'
    | '/listings'
    | '/messages/$id'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/search'
    | '/welcome'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/_authenticated/me'
    | '/_authenticated/sell'
    | '/category/$slug'
    | '/legal/faq'
    | '/legal/guide'
    | '/legal/notices'
    | '/legal/privacy'
    | '/legal/prohibited'
    | '/legal/report'
    | '/legal/terms'
    | '/listings/$id'
    | '/listings/'
    | '/_authenticated/messages/$id'
    | '/_authenticated/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  WelcomeRoute: typeof WelcomeRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LegalFaqRoute: typeof LegalFaqRoute
  LegalGuideRoute: typeof LegalGuideRoute
  LegalNoticesRoute: typeof LegalNoticesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalProhibitedRoute: typeof LegalProhibitedRoute
  LegalReportRoute: typeof LegalReportRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/report': {
      id: '/legal/report'
      path: '/legal/report'
      fullPath: '/legal/report'
      preLoaderRoute: typeof LegalReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/prohibited': {
      id: '/legal/prohibited'
      path: '/legal/prohibited'
      fullPath: '/legal/prohibited'
      preLoaderRoute: typeof LegalProhibitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/notices': {
      id: '/legal/notices'
      path: '/legal/notices'
      fullPath: '/legal/notices'
      preLoaderRoute: typeof LegalNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/guide': {
      id: '/legal/guide'
      path: '/legal/guide'
      fullPath: '/legal/guide'
      preLoaderRoute: typeof LegalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/faq': {
      id: '/legal/faq'
      path: '/legal/faq'
      fullPath: '/legal/faq'
      preLoaderRoute: typeof LegalFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  WelcomeRoute: WelcomeRoute,
  CategorySlugRoute: CategorySlugRoute,
  LegalFaqRoute: LegalFaqRoute,
  LegalGuideRoute: LegalGuideRoute,
  LegalNoticesRoute: LegalNoticesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalProhibitedRoute: LegalProhibitedRoute,
  LegalReportRoute: LegalReportRoute,
  LegalTermsRoute: LegalTermsRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
